### ISSUE TITLE
open source time

### ISSUE THREAD

**Issue by dailing57** [jx-zhong-for-academic-purpose/Multibody_SE3#1]
Wonderful work! How long will it take for the code of this article to be open source?

**Comment by jx-zhong-for-academic-purpose** [comment]
感谢关注！等我5月22号赶完这波deadline，就着手整理，大概一周内上传到这里？

**Comment by dailing57** [comment]
好的好的，太牛辣！

**Comment by jx-zhong-for-academic-purpose** [comment]
> 好的好的，太牛辣！

因为最近都比较忙，如果到时没看到，应该是我忘记了，欢迎随时督促我：）谢谢！

**Comment by dailing57** [comment]
催更一下^_^

**Comment by jx-zhong-for-academic-purpose** [comment]
> 催更一下^_^

Done :)
